# spring:
#     cloud:
#         gateway:
#             routes:
#                 - id: monopatines-service
#                   uri: http://localhost:8002
#                   predicates:
#                     - Path=/monopatines/**
#                   filters:
#                     - PrefixPath=/api
#                 - id: viajes-service
#                   uri: http://localhost:8003
#                   predicates:
#                     - Path=/viajes/**
#                   filters:
#                     - PrefixPath=/api
