server:
  port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: monopatines-service
                  uri: http://localhost:8002
                  predicates:
                    - Path=/monopatines/**
                  
                - id: viajes-service
                  uri: http://localhost:8003
                  predicates:
                    - Path=/viajes/**


